services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./prisma/data:/app/prisma/data
    environment:
      - DATABASE_URL=file:/app/prisma/data/dev.db
    restart: always

volumes:
  prisma_data:
